# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('departamento', models.IntegerField(verbose_name='Departamento')),
                ('codigo', models.IntegerField(verbose_name='C\xf3digo')),
                ('creditos', models.IntegerField(verbose_name='C\xf3digo')),
                ('carga_horaria', models.IntegerField(verbose_name='C\xf3digo')),
                ('carga_horaria_semanal', models.IntegerField(verbose_name='C\xf3digo')),
                ('tipo', models.CharField(choices=[('O', 'Obrigat\xf3ria'), ('U', 'Universal'), ('E', 'Eletiva')], default='U', max_length=1, verbose_name='C\xf3digo')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=5, verbose_name='SIGLA')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.AddField(
            model_name='disciplina',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='controle_academico.Unidade'),
        ),
    ]
