# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidade',
            options={'ordering': ('sigla',), 'verbose_name': 'Unidade', 'verbose_name_plural': 'Unidades'},
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria',
            field=models.IntegerField(verbose_name='Carga Horaria'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='carga_horaria_semanal',
            field=models.IntegerField(verbose_name='Carga Horaria Semanal'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='creditos',
            field=models.IntegerField(verbose_name='Cr\xe9ditos'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='tipo',
            field=models.CharField(choices=[('O', 'Obrigat\xf3ria'), ('U', 'Universal'), ('E', 'Eletiva')], default='U', max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='unidade',
            name='sigla',
            field=models.CharField(max_length=5, verbose_name='Sigla'),
        ),
    ]
