# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_academico', '0003_auto_20160903_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='atual',
            field=models.BooleanField(default=False, verbose_name='Atual'),
        ),
    ]
