# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_academico', '0004_periodo_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinacursada',
            name='professor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Professor'),
        ),
    ]
