# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_academico', '0005_disciplinacursada_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, verbose_name='Sigla')),
                ('inicio', models.TimeField(verbose_name='In\xedcio')),
                ('final', models.TimeField(verbose_name='In\xedcio')),
            ],
            options={
                'verbose_name': 'Hor\xe1rio',
                'verbose_name_plural': 'Hor\xe1rios',
            },
        ),
        migrations.AlterField(
            model_name='disciplinacursada',
            name='situacao',
            field=models.CharField(choices=[('IS', 'Inscri\xe7\xe3o Solicitada'), ('AC', 'Aceito'), ('AP', 'Aprovado'), ('RN', 'Reprovado por Nota'), ('RF', 'Reprovado por Faltas')], default='AC', max_length=2, verbose_name='Situa\xe7\xe3o'),
        ),
    ]
