# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_academico', '0006_auto_20160903_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='final',
            field=models.TimeField(verbose_name='Final'),
        ),
    ]
