# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('controle_academico', '0007_auto_20160903_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(blank=True, max_length=20, null=True, verbose_name='Sala')),
                ('disciplina_cursada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_academico.DisciplinaCursada')),
                ('horario_final', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario_final', to='controle_academico.Horario')),
                ('horario_inicial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario_inicial', to='controle_academico.Horario')),
            ],
            options={
                'verbose_name': 'Hor\xe1rio Aula',
                'verbose_name_plural': 'Hor\xe1rios Aulas',
            },
        ),
    ]
