# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-10 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_academico', '0009_horarioaula_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='aprovado',
            field=models.BooleanField(default=False, verbose_name='Aprovado'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='periodo_sugerido',
            field=models.IntegerField(blank=True, null=True, verbose_name='Per\xedodo'),
        ),
    ]
